"""create currencies table

Revision ID: cf9a680a698f
Revises: 
Create Date: 2023-12-01 00:57:23.918822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cf9a680a698f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_currency", sa.String(), nullable=False),
        sa.Column("to_currency", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("rate", sa.DECIMAL(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_currency",
            "to_currency",
            "date",
            name="unique_pair_from_to_for_date",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency_rates")
    # ### end Alembic commands ###
