"""Create category table

Revision ID: 13ce51a965ec
Revises: 
Create Date: 2023-12-07 02:18:18.273238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "13ce51a965ec"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "description",
            sa.String(),
            server_default="",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("category")
    # ### end Alembic commands ###
