"""Create quote table

Revision ID: 146e1aaa7a17
Revises: 
Create Date: 2023-12-10 21:05:43.165310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "146e1aaa7a17"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quote",
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("text"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote")
    # ### end Alembic commands ###
